import { Section } from '@/types'

export const lessons: Section[] = [
	{
		id: 1,
		title: 'Learn',
		theme: 'blue',
		slug: 'learn',
		units: [
			{
				id: 1,
				title: 'Unit 1',
				slug: 'unit-1',
				type: 'start',
				isCompleted: false,
				isLocked: false,
				item: [
					{
						type: 'flashcard',
						id: 1,
						viewed: false,
						front_side: `afraid`,
						back_side: `Qo'rqqan, cho'chigan`,
						description: `The woman was afraid of what she saw.`,
						synonyms: [``],
						tags: { id: 1, name: 'adjective' },
						image: `/placeholder.svg?height=100&width=100&text=AdvWor`,
					},
					{
						type: 'flashcard',
						id: 2,
						viewed: false,
						front_side: `agree`,
						back_side: `Fikriga qo'shilmoq, rozi bo'lmoq`,
						description: `A: The food is very good in that restaurant. B: I agree with you.`,
						synonyms: [``],
						tags: { id: 2, name: 'verb' },
						image: `/placeholder.svg?height=100&width=100&text=AdvWor`,
					},
					{
						type: 'flashcard',
						id: 3,
						viewed: false,
						front_side: `angry`,
						back_side: `Jahli chiqqan, badjahl`,
						description: `She didn’t do her homework, so her father is angry`,
						synonyms: [``],
						tags: { id: 1, name: 'adjective' },
						image: `/placeholder.svg?height=100&width=100&text=AdvWor`,
					},
					{
						type: 'flashcard',
						id: 4,
						viewed: false,
						front_side: `arrive`,
						back_side: `Yetib kelmoq, kelmoq`,
						description: `The bus always arrives at the corner of my street at 4:00`,
						synonyms: [``],
						tags: { id: 2, name: 'verb' },
						image: `/placeholder.svg?height=100&width=100&text=AdvWor`,
					},
					{
						type: 'flashcard',
						id: 5,
						viewed: false,
						front_side: `attack`,
						back_side: `Hujum qilmoq, hujum uyushtirmoq`,
						description: `The man with the sword attacked the other man first.`,
						synonyms: [``],
						tags: { id: 2, name: 'verb' },
						image: `/placeholder.svg?height=100&width=100&text=AdvWor`,
					},
					{
						type: 'flashcard',
						id: 6,
						viewed: false,
						front_side: `bottom`,
						back_side: `Tag, pastki qism`,
						description: `The bottom of my shoe has a hole in it.`,
						synonyms: [``],
						tags: { id: 3, name: 'noun' },
						image: `/placeholder.svg?height=100&width=100&text=AdvWor`,
					},
					{
						type: 'flashcard',
						id: 7,
						viewed: false,
						front_side: `clever`,
						back_side: `Aqlli, ziyrak`,
						description: `The clever boy thought of a good idea`,
						synonyms: [``],
						tags: { id: 1, name: 'adjective' },
						image: `/placeholder.svg?height=100&width=100&text=AdvWor`,
					},
					{
						type: 'flashcard',
						id: 8,
						viewed: false,
						front_side: `cruel`,
						back_side: `Shafqatsiz, berahm`,
						description: `The cruel man yelled at his sister.`,
						synonyms: [``],
						tags: { id: 1, name: 'adjective' },
						image: `/placeholder.svg?height=100&width=100&text=AdvWor`,
					},
					{
						type: 'flashcard',
						id: 9,
						viewed: false,
						front_side: `finally`,
						back_side: `Axiyri, vanihoyat`,
						description: `He finally crossed the finish line after five hours of running.`,
						synonyms: [``],
						tags: { id: 4, name: 'adverb' },
						image: `/placeholder.svg?height=100&width=100&text=AdvWor`,
					},
					{
						type: 'flashcard',
						id: 10,
						viewed: false,
						front_side: `hide`,
						back_side: `Yashirinmoq, bekinmoq`,
						description: `The other children will hide while you count to 100`,
						synonyms: [``],
						tags: { id: 2, name: 'verb' },
						image: `/placeholder.svg?height=100&width=100&text=AdvWor`,
					},
					{
						type: 'flashcard',
						id: 11,
						viewed: false,
						front_side: `hunt`,
						back_side: `Ov qilmoq, ovlamoq`,
						description: `Long ago, people hunted with bows and arrows.`,
						synonyms: [``],
						tags: { id: 2, name: 'verb' },
						image: `/placeholder.svg?height=100&width=100&text=AdvWor`,
					},
					{
						type: 'flashcard',
						id: 12,
						viewed: false,
						front_side: `lot`,
						back_side: `Juda ko'p`,
						description: `There are a lot of apples in the basket.`,
						synonyms: [``],
						tags: { id: 3, name: 'noun' },
						image: `/placeholder.svg?height=100&width=100&text=AdvWor`,
					},
					{
						type: 'flashcard',
						id: 13,
						viewed: false,
						front_side: `middle`,
						back_side: `O'rta`,
						description: `The Canadian flag has a maple leaf in the middle of it.`,
						synonyms: [``],
						tags: { id: 3, name: 'noun' },
						image: `/placeholder.svg?height=100&width=100&text=AdvWor`,
					},
					{
						type: 'flashcard',
						id: 14,
						viewed: false,
						front_side: `moment`,
						back_side: `Sekund; on, zum`,
						description: `I was only a few moments late for the meeting.`,
						synonyms: [``],
						tags: { id: 3, name: 'noun' },
						image: `/placeholder.svg?height=100&width=100&text=AdvWor`,
					},
					{
						type: 'flashcard',
						id: 15,
						viewed: false,
						front_side: `pleased`,
						back_side: `Hursand, mamnun`,
						description: `She was pleased with the phone call she received.`,
						synonyms: [``],
						tags: { id: 1, name: 'adjective' },
						image: `/placeholder.svg?height=100&width=100&text=AdvWor`,
					},
					{
						type: 'flashcard',
						id: 16,
						viewed: false,
						front_side: `promise`,
						back_side: `Va'da bermoq`,
						description: `He promised to return my key by tomorrow.`,
						synonyms: [``],
						tags: { id: 2, name: 'verb' },
						image: `/placeholder.svg?height=100&width=100&text=AdvWor`,
					},
					{
						type: 'flashcard',
						id: 17,
						viewed: false,
						front_side: `reply`,
						back_side: `Javob bermoq`,
						description: `She asked him what time his meeting was. He replied, “at three.”`,
						synonyms: [``],
						tags: { id: 2, name: 'verb' },
						image: `/placeholder.svg?height=100&width=100&text=AdvWor`,
					},
					{
						type: 'flashcard',
						id: 18,
						viewed: false,
						front_side: `safe`,
						back_side: `Xavfsiz, bexatar`,
						description: `Put on your seat belt in the car to be safe.`,
						synonyms: [``],
						tags: { id: 1, name: 'adjective' },
						image: `/placeholder.svg?height=100&width=100&text=AdvWor`,
					},
					{
						type: 'flashcard',
						id: 19,
						viewed: false,
						front_side: `trick`,
						back_side: `Xiyla, nayrang; fokus`,
						description: `His card trick really surprised us.`,
						synonyms: [``],
						tags: { id: 3, name: 'noun' },
						image: `/placeholder.svg?height=100&width=100&text=AdvWor`,
					},
					{
						type: 'flashcard',
						id: 20,
						viewed: false,
						front_side: `well`,
						back_side: `Yaxshi`,
						description: `The couple can dance quite well.`,
						synonyms: [``],
						tags: { id: 4, name: 'adverb' },
						image: `/placeholder.svg?height=100&width=100&text=AdvWor`,
					},
				],
			},
			{
				id: 2,
				title: 'Unit 2',
				slug: 'unit-2',
				type: 'star',
				isCompleted: false,
				isLocked: true,
				item: [
					{
						type: 'wordPair',
						id: 1,
						viewed: false,
						value: `afraid`,
						pair: `Qo'rqqan, cho'chigan`,
					},
					{
						type: 'wordPair',
						id: 2,
						viewed: false,
						value: `agree`,
						pair: `Fikriga qo'shilmoq, rozi bo'lmoq`,
					},
					{
						type: 'wordPair',
						id: 3,
						viewed: false,
						value: `angry`,
						pair: `Jahli chiqqan, badjahl`,
					},
					{
						type: 'wordPair',
						id: 4,
						viewed: false,
						value: `arrive`,
						pair: `Yetib kelmoq, kelmoq`,
					},
					{
						type: 'wordPair',
						id: 5,
						viewed: false,
						value: `attack`,
						pair: `Hujum qilmoq, hujum uyushtirmoq`,
					},
					{
						type: 'wordPair',
						id: 6,
						viewed: false,
						value: `bottom`,
						pair: `Tag, pastki qism`,
					},
					{
						type: 'wordPair',
						id: 7,
						viewed: false,
						value: `clever`,
						pair: `Aqlli, ziyrak`,
					},
					{
						type: 'wordPair',
						id: 8,
						viewed: false,
						value: `cruel`,
						pair: `Shafqatsiz, berahm`,
					},
					{
						type: 'wordPair',
						id: 9,
						viewed: false,
						value: `finally`,
						pair: `Axiyri, vanihoyat`,
					},
					{
						type: 'wordPair',
						id: 10,
						viewed: false,
						value: `hide`,
						pair: `Yashirinmoq, bekinmoq`,
					},
					{
						type: 'wordPair',
						id: 11,
						viewed: false,
						value: `hunt`,
						pair: `Ov qilmoq, ovlamoq`,
					},
					{
						type: 'wordPair',
						id: 12,
						viewed: false,
						value: `lot`,
						pair: `Juda ko'p`,
					},
					{
						type: 'wordPair',
						id: 13,
						viewed: false,
						value: `middle`,
						pair: `O'rta`,
					},
					{
						type: 'wordPair',
						id: 14,
						viewed: false,
						value: `moment`,
						pair: `Sekund; on, zum`,
					},
					{
						type: 'wordPair',
						id: 15,
						viewed: false,
						value: `pleased`,
						pair: `Hursand, mamnun`,
					},
					{
						type: 'wordPair',
						id: 16,
						viewed: false,
						value: `promise`,
						pair: `Va'da bermoq`,
					},
					{
						type: 'wordPair',
						id: 17,
						viewed: false,
						value: `reply`,
						pair: `Javob bermoq`,
					},
					{
						type: 'wordPair',
						id: 18,
						viewed: false,
						value: `safe`,
						pair: `Xavfsiz, bexatar`,
					},
					{
						type: 'wordPair',
						id: 19,
						viewed: false,
						value: `trick`,
						pair: `Xiyla, nayrang; fokus`,
					},
					{
						type: 'wordPair',
						id: 20,
						viewed: false,
						value: `well`,
						pair: `Yaxshi`,
					},
				],
			},
			{
				id: 3,
				title: 'Unit 3',
				slug: 'unit-3',
				type: 'star',
				isCompleted: false,
				isLocked: true,
				item: [
					{
						type: 'fillInBlank',
						id: 1,
						viewed: false,
						options: [`afraid`, `happy`, `excited`],
						question: `She was ___ to walk alone in the dark.`,
						correctAnswer: `afraid`,
					},
					{
						type: 'fillInBlank',
						id: 2,
						viewed: false,
						options: [`agree`, `argue`, `deny`],
						question: `I ___ with you. This is a great idea.`,
						correctAnswer: `agree`,
					},
					{
						type: 'fillInBlank',
						id: 3,
						viewed: false,
						options: [`angry`, `happy`, `kind`],
						question: `He was very ___ because his bike was stolen.`,
						correctAnswer: `angry`,
					},
					{
						type: 'fillInBlank',
						id: 4,
						viewed: false,
						options: [`arrives`, `goes`, `walks`],
						question: `The train always ___ at 7 o’clock.`,
						correctAnswer: `arrives`,
					},
					{
						type: 'fillInBlank',
						id: 5,
						viewed: false,
						options: [`attack`, `play`, `call`],
						question: `The tiger tried to ___ its prey.`,
						correctAnswer: `attack`,
					},
					{
						type: 'fillInBlank',
						id: 6,
						viewed: false,
						options: [`top`, `middle`, `bottom`],
						question: `There is a small hole at the ___ of the bucket.`,
						correctAnswer: `bottom`,
					},
					{
						type: 'fillInBlank',
						id: 7,
						viewed: false,
						options: [`clever`, `lazy`, `silly`],
						question: `That was a very ___ solution to the problem!`,
						correctAnswer: `clever`,
					},
					{
						type: 'fillInBlank',
						id: 8,
						viewed: false,
						options: [`cruel`, `kind`, `gentle`],
						question: `It was ___ of him to hurt the animal.`,
						correctAnswer: `cruel`,
					},
					{
						type: 'fillInBlank',
						id: 9,
						viewed: false,
						options: [`finally`, `suddenly`, `quickly`],
						question: `He ___ finished the long race after three hours.`,
						correctAnswer: `finally`,
					},
					{
						type: 'fillInBlank',
						id: 10,
						viewed: false,
						options: [`hide`, `find`, `run`],
						question: `Let’s ___ behind the tree during the game.`,
						correctAnswer: `hide`,
					},
					{
						type: 'fillInBlank',
						id: 11,
						viewed: false,
						options: [`hunt`, `sleep`, `play`],
						question: `People used to ___ animals for food.`,
						correctAnswer: `hunt`,
					},
					{
						type: 'fillInBlank',
						id: 12,
						viewed: false,
						options: [`lot`, `some`, `few`],
						question: `There are a ___ of books on the shelf.`,
						correctAnswer: `lot`,
					},
					{
						type: 'fillInBlank',
						id: 13,
						viewed: false,
						options: [`middle`, `edge`, `side`],
						question: `There is a red circle in the ___ of the flag.`,
						correctAnswer: `middle`,
					},
					{
						type: 'fillInBlank',
						id: 14,
						viewed: false,
						options: [`moment`, `hour`, `day`],
						question: `Wait a ____, I’ll be right there.`,
						correctAnswer: `moment`,
					},
					{
						type: 'fillInBlank',
						id: 15,
						viewed: false,
						options: [`pleased`, `worried`, `angry`],
						question: `She was very ___ with the gift.`,
						correctAnswer: `pleased`,
					},
					{
						type: 'fillInBlank',
						id: 16,
						viewed: false,
						options: [`promise`, `say`, `ask`],
						question: `He made a ___ to always help his friends.`,
						correctAnswer: `promise`,
					},
					{
						type: 'fillInBlank',
						id: 17,
						viewed: false,
						options: [`reply`, `listen`, `think`],
						question: `If someone asks a question, you should ___ politely.`,
						correctAnswer: `reply`,
					},
					{
						type: 'fillInBlank',
						id: 18,
						viewed: false,
						options: [`safe`, `dangerous`, `hot`],
						question: `Wear a helmet to stay ___.`,
						correctAnswer: `safe`,
					},
					{
						type: 'fillInBlank',
						id: 19,
						viewed: false,
						options: [`trick`, `game`, `puzzle`],
						question: `He played a funny ___ on his brother.`,
						correctAnswer: `trick`,
					},
					{
						type: 'fillInBlank',
						id: 20,
						viewed: false,
						options: [`well`, `badly`, `hard`],
						question: `She sings very ___.`,
						correctAnswer: `well`,
					},
				],
			},
		],
	},
]
