import { Section } from '@/types'

export const lessons: Section[] = [
	{
		id: 1,
		title: 'Basic Vocabulary',
		theme: 'blue',
		slug: 'basic-vocabulary',
		units: [
			{
				id: 1,
				title: 'Unit 1',
				slug: 'unit-1',
				type: 'start',
				isCompleted: false,
				isLocked: false,
				item: [
					{
						type: 'flashcard',
						id: 10,
						viewed: false,
						front_side: `Advanced Word `,
						back_side: `Advanced Definition `,
						description: `Complex example sentence for Advanced Word `,
						synonyms: [`Advanced Synonym A`, `Advanced Synonym B`],
						tags: { id: 2, name: 'verb' },
						image: `/placeholder.svg?height=100&width=100&text=AdvWor `,
					},
					{
						type: 'flashcard',
						id: 11,
						viewed: false,
						front_side: `Advanced Word `,
						back_side: `Advanced Definition `,
						description: `Complex example sentence for Advanced Word `,
						synonyms: [`Advanced Synonym A`, `Advanced Synonym B`],
						tags: { id: 2, name: 'verb' },
						image: `/placeholder.svg?height=100&width=100&text=AdvWor `,
					},
				],
			},
			{
				id: 2,
				title: 'Unit 2',
				slug: 'unit-2',
				type: 'star',
				isCompleted: false,
				isLocked: true,
				item: [
					{
						type: 'imageSelection',
						id: 1,
						viewed: false,
						word: `banan`,
						question: `Choose words`,
						options: [
							{
								id: '1',
								image: 'https://picsum.photos/200',
								label: `milk`,
							},
							{
								id: '2',
								image: 'https://picsum.photos/200',
								label: `apple`,
							},
							{
								id: '3',
								image: 'https://picsum.photos/200',
								label: `banana`,
							},
						],
						correct: `3`,
					},
					{
						type: 'imageSelection',
						id: 12,
						viewed: false,
						word: `banan`,
						question: `Choose words`,
						options: [
							{
								id: '1',
								image: 'https://picsum.photos/200',
								label: `milk`,
							},
							{
								id: '2',
								image: 'https://picsum.photos/200',
								label: `apple`,
							},
							{
								id: '3',
								image: 'https://picsum.photos/200',
								label: `banana`,
							},
						],
						correct: `3`,
					},
				],
			},
			{
				id: 3,
				title: 'Unit 3',
				slug: 'unit-3',
				type: 'star',
				isCompleted: false,
				isLocked: true,
				item: Array.from({ length: 2 }, (_, j) => ({
					type: 'wordPair',
					id: j + 1,
					viewed: false,
					value: `Advanced Word ${j + 1}`,
					pair: `Advanced Translation ${j + 1}`,
				})),
			},
			{
				id: 4,
				title: 'Unit 4',
				slug: 'unit-4',
				type: 'star',
				isCompleted: false,
				isLocked: true,
				item: Array.from({ length: 2 }, (_, j) => ({
					type: 'fillInBlank',
					id: j + 1,
					viewed: false,
					options: [`go`, `goes`, `going`],
					question: `I ___ to the park every morning.`,
					correctAnswer: `go`,
				})),
			},
			{
				id: 5,
				title: 'Unit 5',
				slug: 'unit-5',
				type: 'star',
				isCompleted: false,
				isLocked: true,
				item: Array.from({ length: 2 }, (_, j) => ({
					type: 'finishQuiz',
					id: j + 1,
					viewed: false,
					en: `hi`,
					uz: `salom`,
				})),
			},
		],
	},
]
