import type { Section as SectionType } from '@/types'

export const initialSections: SectionType[] = [
	{
		id: 1,
		title: 'Discuss traveling solo',
		theme: 'pink',
		units: [
			{
				id: 1,
				title: 'Start',
				slug: 'unit-1',
				type: 'start',
				isCompleted: false,
				isLocked: false,
			},
			{
				id: 2,
				title: 'Basic Phrases',
				slug: 'unit-2',
				type: 'star',
				isCompleted: false,
				isLocked: true,
			},
			{
				id: 3,
				title: 'Practice',
				slug: 'unit-3',
				type: 'character',
				isCompleted: false,
				isLocked: true,
			},
			{
				id: 4,
				title: 'Challenge',
				type: 'chest',
				slug: 'unit-4',
				isCompleted: false,
				isLocked: true,
			},
			{
				id: 5,
				title: 'Complete',
				slug: 'unit-5',
				type: 'trophy',
				isCompleted: false,
				isLocked: true,
			},
		],
	},
	{
		id: 2,
		title: 'Order food delivery',
		theme: 'pink-dark',
		units: [
			{
				id: 1,
				title: 'Start',
				type: 'start',
				slug: 'unit-1',
				isCompleted: false,
				isLocked: false,
			},
			{
				id: 2,
				title: 'Menu Items',
				type: 'star',
				slug: 'unit-2',
				isCompleted: false,
				isLocked: true,
			},
			{
				id: 3,
				title: 'Practice',
				type: 'character',
				slug: 'unit-3',
				isCompleted: false,
				isLocked: true,
			},
			{
				id: 4,
				title: 'Challenge',
				type: 'chest',
				slug: 'unit-4',
				isCompleted: false,
				isLocked: true,
			},
			{
				id: 5,
				title: 'Complete',
				slug: 'unit-5',
				type: 'trophy',
				isCompleted: false,
				isLocked: true,
			},
		],
	},
	{
		id: 3,
		title: 'Navigate public transportation',
		theme: 'purple',
		units: [
			{
				id: 1,
				title: 'Start',
				type: 'start',
				slug: 'unit-1',
				isCompleted: false,
				isLocked: false,
			},
			{
				id: 2,
				title: 'Transit Vocabulary',
				type: 'star',
				slug: 'unit-2',
				isCompleted: false,
				isLocked: true,
			},
			{
				id: 3,
				title: 'Practice',
				slug: 'unit-3',
				type: 'character',
				isCompleted: false,
				isLocked: true,
			},
			{
				id: 4,
				title: 'Challenge',
				type: 'chest',
				slug: 'unit-4',
				isCompleted: false,
				isLocked: true,
			},
			{
				id: 5,
				title: 'Complete',
				slug: 'unit-5',
				type: 'trophy',
				isCompleted: false,
				isLocked: true,
			},
		],
	},
	{
		id: 4,
		title: 'Book accommodation',
		theme: 'blue',
		units: [
			{
				id: 1,
				title: 'Start',
				slug: 'unit-1',
				type: 'start',
				isCompleted: false,
				isLocked: false,
			},
			{
				id: 2,
				title: 'Accommodation Types',
				slug: 'unit-2',
				type: 'star',
				isCompleted: false,
				isLocked: true,
			},
			{
				id: 3,
				title: 'Practice',
				slug: 'unit-3',
				type: 'character',
				isCompleted: false,
				isLocked: true,
			},
			{
				id: 4,
				title: 'Challenge',
				slug: 'unit-4',
				type: 'chest',
				isCompleted: false,
				isLocked: true,
			},
			{
				id: 5,
				title: 'Complete',
				slug: 'unit-5',
				type: 'trophy',
				isCompleted: false,
				isLocked: true,
			},
		],
	},
]
